#!/usr/bin/python3
from subprocess import Popen, PIPE
import re

acpi = Popen(['acpi', '-b'], stdout=PIPE)
match = re.match('^Battery (\d+): (\w+), (\d+)%(?:, (\d{2}:\d{2}:\d{2}) \w+)$', \
	acpi.communicate()[0].decode())
match or exit()

status  = match.group(2)
percent = int(match.group(3))
if   percent < 25:
	color = '#FF0000'
	icon  = ''
elif percent < 50:
	color = '#FFF600'
	icon  = ''
elif percent < 85:
	color = '#A8FF00'
	icon  = ''
else:
	color = '#A8FF00'
	icon  = ''

percent = str(percent)
text = f"<span color='{color}'>{icon}</span>" \
	+ (' ' * (4 - len(percent))) \
	+ percent + '%'

if status == 'Charging' or status == 'Full':
	text += ' ';
elif status == 'Discharging':
	text += ' ('+match.group(4)+')'

print(text)
