#!/usr/bin/python3
from subprocess import Popen, PIPE
import os
import re

route = Popen(['ip', 'route'], stdout=PIPE)
route = route.communicate()[0].decode()
match = re.match('default via (\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}) dev (\w+)', route)
match or exit()

dev = match.group(2)
ip  = match.group(1)

try:
	if os.path.exists(f'/sys/class/net/{dev}/wireless'):
		with(open("/proc/net/wireless", 'r')) as signal_info:
			match = re.match(f'{dev}: \d+ \s*(\d+)', signal_info.read())
			signal = float(match.group(1))
			signal = int(signal * 100. / 70. + .5)
			print(ip + ' ' + signal)
	print(ip)
except IOError:
	print(ip)
