#!/usr/bin/perl

use strict;
use warnings;
use utf8;

my $button = $ARGV[0] || $ENV{'block_button'} || 1;
my $output;
my $args;

if($button == 1) {
	my @outputs = (`xrandr` =~ /(\w+) connected/g);
	if(scalar @outputs == 1) {
		$output = @outputs[0];
	} else {
		$args = join "\n", @outputs;
		$output = `echo "$args" | rofi -dmenu`;
		$output =~ s/\s+$//;
	}
	
	if($output ne '') {
		foreach(@outputs) {
			if($_ ne $output) {
				`xrandr --output $_ --off`;
			}
		}
		`xrandr --output $output --auto --primary`;
		`notify-send "Using monitor: $output"`;
		if($output =~ m/HDMI/) {
			`xrandr --output $output --set 'Broadcast RGB' Full --set audio on`;
		}
	}
}
