#!/usr/bin/python
from subprocess import Popen, PIPE, run
import re

xrandr = Popen(['xrandr'], stdout=PIPE)
output_str = xrandr.communicate()[0].decode()
output_re = re.finditer('(\w+) connected', output_str)
outputs = list(map(lambda m: m.group(1), output_re))

if len(outputs) == 1:
	choice = outputs[0]
else:
	args = "\n".join(outputs)
	rofi = Popen(['rofi', '-dmenu', '-p', ' '], \
		stdin=PIPE, stdout=PIPE)
	choice = rofi.communicate(args.encode())[0].decode()[:-1]
		
cmd = ['xrandr']
for output in outputs:
	if output != choice:
		cmd.extend(['--output', output, '--off'])

if choice != '':
	cmd.extend(['--output', choice, '--auto', '--primary'])
	if re.match('LVDS', choice):
		cmd.extend(['--dpi', '90'])
	elif re.match('HDMI', choice):
		cmd.extend(['--dpi', '96', \
			'--set', 'Broadcast RGB', 'Full', \
			'--set', 'audio', 'on'])

run(cmd)
run(['xrandr', '-s', '0'])
run(['notify-send', 'Output', 'Using monitor: ' + choice])

