#!/usr/bin/python3
from subprocess import Popen, PIPE, run
import time
import os
import re

def sink_volume():
	pacmd = Popen(['pacmd', 'list-sinks'], stdout=PIPE)
	pacmd = pacmd.communicate()[0].decode()

	sink = re.search('\* index: (\d+)', pacmd) or exit()
	end = pacmd.index('properties:', sink.start())
	pacmd = pacmd[sink.start() : end]
	sink = sink.group(1)

	volume = int(re.search('volume: front-left: \d+ / +(\d+)%', pacmd).group(1))
	muted  = re.search('muted: (yes|no)', pacmd).group(1)
	return (sink, volume, muted == 'yes')

button = int(os.getenv('BLOCK_BUTTON') or 0)
volume = sink_volume()

if button != 0:
	if   button == 3:
		run(['pactl', 'set-sink-mute', volume[0], 'toggle'])
	elif button == 4:
		run(['pactl', 'set-sink-volume', volume[0], '+5%'])
	elif button == 5:
		run(['pactl', 'set-sink-volume', volume[0], '-5%'])
	pacmd = Popen(['pacmd', 'list-sinks'], stdout=PIPE)
	pacmd = pacmd.communicate()[0].decode()[sink_start:]
	volume = sink_volume()

if volume[2]:
	icon = ''
elif volume[1] < 35:
	icon = ''
else:
	icon = ''

volume = str(volume[1])
print(icon + (' ' * (4 - len(volume))) + volume + '%')
