#!/usr/bin/perl

use strict;
use warnings;
use utf8;
use open ':std', ':encoding(UTF-8)';

my $button = defined $ARGV[0] ?
	$ARGV[0] :
	(defined $ENV{'BLOCK_BUTTON'} ? $ENV{'BLOCK_BUTTON'} : 0);

my $sink_data = `pacmd list-sinks`;
$sink_data =~ /\* index: (\d+)/;
my $sink = $1;

if($button != 0) {
	if($button == 3) { `pactl set-sink-mute $sink toggle`; }
	elsif($button == 4) { `pactl set-sink-volume $sink +5%`; }
	elsif($button == 5) { `pactl set-sink-volume $sink -5%`; }
	$sink_data = `pacmd list-sinks`;
}

$sink_data =~ /volume:.*?([0-9]+)%/;
my $volume = $1;
$sink_data =~ /muted: (yes|no)/;
my $muted = $1;

if(defined $ARGV[0]) {
	`pkill -RTMIN+10 i3blocks`;
	# exit(0);
}

my $text;
if($muted eq 'yes') { $text = ''; }
elsif($volume < 35) { $text = ''; }
else				{ $text = ''; }
$text .= (' ' x (length $volume - 4))."$volume%\n";

print $text.$text;